### ISSUE TITLE
Octo Expansion Deletes itself WTF did I do wrong?

### ISSUE THREAD

**Issue by Hectoling** [SunTheCourier/Splatoon-2-Meme-ROM-hack#11]

**Comment by shadowninja108** [comment]
What do you mean "deletes itself"? Was the DLC uninstalled?

**Comment by Hectoling** [comment]
Yes only when the hack is on.

**Comment by shadowninja108** [comment]
Still pretty unclear, do you mean that the game acts like the DLC doesn't exist?

**Comment by SunTheCourier** [comment]
What does the game display when attempting to open up Octo Expansion?

**Comment by tumGER** [comment]
There is nothing in this pack that could cause this

**Comment by SunTheCourier** [comment]
it could be an issue with your sd files

**Comment by SunTheCourier** [comment]
There has been no response for a while so I'm closing this issue. If you still need help you can get help here: https://discord.gg/5k4msvP
